spring:
    application:
        name: spring-boot-oauth2-client
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header
logging:
    level:
     org.springframework.security: DEBUG

server:
    port: 8081
    error:
        whitelabel:
            enabled: false
oauth:
  server:
    checkToken:
      uri: http://localhost:8080/oauth/check_token            
#https://github.com/aldwindelgado/spring-boot-oauth2-client            